# Generated by Django 4.1 on 2022-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('match_id', models.IntegerField()),
                ('description', models.TextField()),
                ('embed_code', models.URLField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-match_id'],
            },
        ),
    ]
