# Generated by Django 4.1 on 2022-08-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='matches',
            name='match_id',
        ),
    ]
